{
 "title": "Apache",
 "description": "Apache Prometheus Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(apache_up, instance)"
    }
   },
   {
    "name": "port",
    "query": {
     "query": "label_values(apache_up, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apache_uptime_seconds_total{instance=~\"$host:$port\"}"
    }
   ]
  },
  {
   "title": "Apache Up / Down",
   "type": "graph",
   "gridPos": { "h": 3, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(apache_up{instance=~\"$host:$port\"} == 1)",
     "legendFormat": "Apache Up"
    },
    {
     "expr": "scalar(count(apache_up{instance=~\"$host:$port\"} == 0))",
     "legendFormat": "Apache Down"
    }
   ]
  },
  {
   "title": "Current total kbytes sent",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "rate(apache_sent_kilobytes_total{instance=~\"$host:$port\"}[5m])",
     "legendFormat": "Kilobytes Sent"
    }
   ]
  },
  {
   "title": "Current total apache accesses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(apache_accesses_total{instance=~\"$host:$port\"}[5m])",
     "legendFormat": "Accesses"
    }
   ]
  },
  {
   "title": "Apache scoreboard statuses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apache_scoreboard{instance=~\"$host:$port\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Apache worker statuses",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apache_workers{instance=~\"$host:$port\"}\n",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Apache CPU load",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apache_cpuload{instance=~\"$host:$port\"}",
     "legendFormat": "Load"
    }
   ]
  }
 ]
}